server:
  port: 8484
spring:
  application:
    name: invoice-service
  kafka:
    consumer:
      group-id: invoice-group-1
      auto-offset-reset: earliest
      bootstrap-servers: localhost:29092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
